hydra:
  job:
    chdir: True
  run:
    dir: ./outputs_pino

start_lr: 0.001
gamma: 0.99948708
max_epochs: 50

model:
  fno:
    in_channels: 1
    out_channels: 1
    decoder_layers: 1
    decoder_layer_size: 32
    dimension: 2
    latent_channels: 32
    num_fno_layers: 4
    num_fno_modes: 12
    padding: 9